### ISSUE TITLE
php weathermapper.php

### ISSUE THREAD

**Issue by geyson2911** [pblasquez/weathermapper#24]
returning with syntax error

librenms@XX:/opt/weathermapper$ php weathermapper.php
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
      AND d2.hostname IN ('')
       AND p.ifType IN ('ethernetCsmacd','iee...' at line 18 in /opt/weathermapper/includes/weathermapper.inc.php:355
Stack trace:
#0 /opt/weathermapper/includes/weathermapper.inc.php(355): PDOStatement->execute()
#1 /opt/weathermapper/weathermapper.php(36): get_link_matrix()
#2 {main}
  thrown in /opt/weathermapper/includes/weathermapper.inc.php on line 355
librenms@177-104-115-100:/opt/weathermapper$ nano /opt/weathermapper/includes/weathermapper.inc.php

**Comment by ImPias** [comment]
Myself also facing the same issue. Did you got any solution? @geyson2911

**Comment by p-rintz** [comment]
I thought Id mention that this happens if you use group based weathermaps for example without having a group actually created in LibreNMS.

Solution: Create a group.
