### ISSUE TITLE
php /opt/weathermapper/weathermapper.php NOT FOUND!

### ISSUE THREAD

**Issue by mrlopezbpa** [pblasquez/weathermapper#27]
Hello, first of all I apologize for my lousy English, secondly I am new to this and I want to install Weathermap and Weathermapper, I already have the first one working, I followed all the steps to install Weathermapper without problems. When executing this via CLI it throws me the following error:

```
librenms@librenms:~$ php /opt/weathermapper/weathermapper.php
$label = 'mylabel';
$weathermapper[$label] = [];
$weathermapper[$label]['title'] = "Network Map (".$label.")";
$weathermapper[$label]['grid_opts'] = $grid_opts;
$weathermapper[$label]['search_opts'] = [];
$weathermapper[$label]['search_opts']['types'] = ['hostname'];
$weathermapper[$label]['search_opts']['hostnames'] = [];
$weathermapper[$label]['search_opts']['hostnames'][] = [
  'regex' => "myhost[0-9]+.*",
  'row' => 10
];
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
      AND d2.hostname IN ('')
       AND p.ifType IN ('ethernetCsmacd','iee...' at line 18 in /opt/weathermapper/includes/weathermapper.inc.php:355
Stack trace:
#0 /opt/weathermapper/includes/weathermapper.inc.php(355): PDOStatement->execute()
#1 /opt/weathermapper/weathermapper.php(34): get_link_matrix()
#2 {main}
  thrown in /opt/weathermapper/includes/weathermapper.inc.php on line 355

```
Could you help me to solve them.
From already thank you very much for your time.

**Comment by p-rintz** [comment]
You have the same issue as #24 

Problem is that your hostname regex doesnt seem to be matching any devices.
